### ISSUE TITLE
Pridat odkaz na predesle akce v hlavicce

### ISSUE THREAD

**Issue by lspdv** [TwistoPayments/backendisti.cz#2]
Ne kazdy to najde na konci udalosti a spousty lidi hleda vase super videa :-)))

<img width="1282" alt="screen shot 2017-02-13 at 19 36 19" src="https://cloud.githubusercontent.com/assets/12471149/22897464/f363556e-f223-11e6-9b57-d4cfde142180.png">

**Comment by ViktorStiskala** [comment]
Díky, přidali jsme do odkazů.

**Comment by lspdv** [comment]
To je skvele, diky a povim to lidem co se zajimali :-)

Dne pátek 17. února 2017 Viktor Stískala <notifications@github.com>
napsal(a):
